# NUMPY  ARRAY


In [1]:
import numpy as nm  
# importing library as alias name 

In [2]:
import math    # impporting library

In [3]:
math.sqrt(25)

5.0

In [5]:
import math as m


In [221]:
m.sqrt(25)

5.0

In [7]:
m.pow(5,3)

125.0

In [16]:
from math import sqrt # fro importing particular fun from library

In [17]:
sqrt(100)

10.0

In [3]:
import numpy as np

In [4]:
l3=[1,2,3]

In [13]:
arr1=np.array(l3)    # convert in array from list using numpy library
                     # library.function(variable)

In [14]:
arr1=np.array([1,2,3])

In [15]:
arr1

array([1, 2, 3])

In [271]:
type(arr1) # ndarray means n dimentional array 

numpy.ndarray

In [5]:
l3

[1, 2, 3]

In [6]:
l4=[3,2,1]

In [13]:
l=[l3,l4]
l

[[1, 2, 3], [3, 2, 1]]

In [14]:
arr=np.array(l)   # from m dimentional array
arr

array([[1, 2, 3],
       [3, 2, 1]])

In [25]:
arr1=np.array([[1,2,3],[3,2,1]])

In [26]:
arr1

array([[1, 2, 3],
       [3, 2, 1]])

In [24]:
arr      # in array we can store multiple values along with multiple dimentional values

array([[1, 2, 3],
       [3, 2, 1]])

In [11]:
l5=[45,4,5]
l=[l3,l4,l5]
arr1=np.array(l)            # we can make multi dimentional array through passing a list
arr1

array([[ 1,  2,  3],
       [ 3,  2,  1],
       [45,  4,  5]])

### property of array:- it is only one data type,if list then list etc.


highest priorty given to srtring when in hetrogeneous list is there 

In [280]:
nm.arange(10)    # for give range of number in array called array range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
nm.arange()        #put value at what we want to print as range

TypeError: arange() missing required argument 'start' (pos 1)

In [14]:
nm.arange(2,10)        #start,end

array([2, 3, 4, 5, 6, 7, 8, 9])

In [284]:
nm.arange(5,15,2)       # start,end,step

array([ 5,  7,  9, 11, 13])

In [3]:
import numpy as np

In [12]:
b=np.arange(13,131,13)    #start,end,step
list(b)

[13, 26, 39, 52, 65, 78, 91, 104, 117, 130]

In [16]:
np.arange(1,10).reshape(3,3)      # converting into 2d 3column ,3 rows matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
n=np.arange(1,26).reshape(5,5)     #reshape is used for reshaping and conversion into matrix

In [34]:
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [297]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [301]:
np.arange(1,101).reshape(5,20)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

In [19]:
np.arange(1,101).reshape(1,100)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [304]:
n=np.arange(1,26).reshape(5,5)

In [35]:
n.shape      # for checking rows and column or matrix size use shape command

(5, 5)

In [36]:
n.ndim              # retun dimention of array use ndim

2

In [38]:
n.shape [0]   #  it will return no of rows by using indexing

5

In [312]:
n.shape [1]    # it will return no of column by using indexing

5

In [315]:
m=np.arange(1,16).reshape(5,3)         # reshape (row,coloumn)

In [316]:
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [317]:
m.ndim

2

In [318]:
m.shape

(5, 3)

In [21]:
a=np.arange(10)

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a.shape    # return default count of element(rows ) only in array as this is 1 dimentional but in 2D it will return rows and column

(10,)

### trick ,if any output is showing after command then it will be temporary for output only not change or permanent 

In [19]:
l=[[1,2,3,4]]    # nested list or 2D list  if we put list under a list then it will be a 2D array
l

[[1, 2, 3, 4]]

In [20]:
a=np.array(l)

In [21]:
a      # as output it shows [[]] list under a list

array([[1, 2, 3, 4]])

In [22]:
a.shape

(1, 4)

In [23]:
a.ndim

2

In [22]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
a[0]

array([1, 2, 3, 4, 5])

In [340]:
a[1]

array([ 6,  7,  8,  9, 10])

In [341]:
a[2]

array([11, 12, 13, 14, 15])

In [342]:
a[3]

array([16, 17, 18, 19, 20])

In [343]:
a[0][0]

1

In [25]:
a[0,0]      #ALSO write as [rows,column]

1

In [345]:
a[0,1] #method 2

2

In [346]:
a[3,3]   # if fetching 19

19

In [348]:
a[1:4]   #from [start:end]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [349]:
a[::-1]

array([[21, 22, 23, 24, 25],
       [16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [352]:
a[::-1][::-1]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [355]:
a[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [356]:
a[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [358]:
a[:,0]       # for selecting column of 1st   # [all rows,column]

array([ 1,  6, 11, 16, 21])

In [359]:
a[:,1]

array([ 2,  7, 12, 17, 22])

In [366]:
a[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [367]:
a[:,[0]]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [372]:
a[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [376]:
a[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [379]:
b=np.arange(1,101).reshape(10,10)
b

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [383]:
b[::2]      # [start:stop+1:step size 2]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90]])

In [385]:
b[::3]    # step3 will skip 2 and return each third value as step size is 3 here

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [386]:
b[1:6:2]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [388]:
b[:,1:6:2]             #for column 

array([[ 2,  4,  6],
       [12, 14, 16],
       [22, 24, 26],
       [32, 34, 36],
       [42, 44, 46],
       [52, 54, 56],
       [62, 64, 66],
       [72, 74, 76],
       [82, 84, 86],
       [92, 94, 96]])

In [389]:
b[::-1]  #reverse the rows

array([[ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [  1,   2,   3,   4,   5,   6,   7,   8,   9,  10]])

In [390]:
b[:,::-1]   # reverse column 

array([[ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91]])

In [391]:
b[::-1,::-1]        # first change rows then column not transpose

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91],
       [ 90,  89,  88,  87,  86,  85,  84,  83,  82,  81],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 70,  69,  68,  67,  66,  65,  64,  63,  62,  61],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 30,  29,  28,  27,  26,  25,  24,  23,  22,  21],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

In [393]:
b.T   # for transpose array row=column and column=row conversion

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [28]:
a=np.arange(1,7).reshape(2,3)

In [29]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [400]:
a.shape

(2, 3)

In [30]:
a.ndim

2

In [32]:
b=a.T   # transpose and convert rows into column and viceversa
b           # its(3,2)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [33]:
b.shape

(3, 2)

In [34]:
b.ndim

2

In [402]:
np.dot(a,b)   # method 1

array([[14, 32],
       [32, 77]])

In [404]:
a@b       # method 2 for dot product  using @ 

array([[14, 32],
       [32, 77]])

In [23]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
b=a+1
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [25]:
a+10      # every element by value

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [26]:
a-1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
a*10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [413]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [414]:
1/a

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [416]:
a**2    # *strik

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [418]:
a*-1

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [35]:
a=np.arange(2,11).reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [36]:
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [423]:
a+b

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [425]:
a*b

array([[  6,  12,  20],
       [ 30,  42,  56],
       [ 72,  90, 110]])

In [426]:
a/b

array([[0.66666667, 0.75      , 0.8       ],
       [0.83333333, 0.85714286, 0.875     ],
       [0.88888889, 0.9       , 0.90909091]])

In [427]:
a**b

array([[         8,         81,       1024],
       [     15625,     279936,    5764801],
       [ 134217728, -808182895, 1215752192]], dtype=int32)

In [433]:
a**(2*b)

array([[         64,        6561,     1048576],
       [  244140625,  1054752768, -1526366847],
       [          0,   689956897, -1304428544]], dtype=int32)

In [28]:
a=np.arange(1,7).reshape(2,3)
a                                #for particular range of arrays with reshape in matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
c=np.array([2,3]).reshape(2,1)      #defined data as list passed through array with reshape in matrix
c

array([[2],
       [3]])

In [30]:
a*c

array([[ 2,  4,  6],
       [12, 15, 18]])

In [35]:
d=np.arange(0,4).reshape(2,2)
d

array([[0, 1],
       [2, 3]])

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a*d    #not working for more than 1*1 matrix  as not same no. of elements are there in both tables

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [48]:
np.zeros(5)    #return zero matrix of float type

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros([6,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [1]:
a=np.ones(9)       #return one's matrix of float type
a.reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
a*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [50]:
np.zeros(5,dtype=int)  #convert float into int

array([0, 0, 0, 0, 0])

In [40]:
np.eye(5)        # for identity matrix of float type

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.eye(5,dtype=int)     #change datatype from float to int

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [51]:
a=np.arange(1,10).reshape(3,3)

In [52]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
a.sum()  # sum of all no. present in matrix

45

In [54]:
a.mean()

5.0

In [55]:
a.var()

6.666666666666667

In [57]:
sqrt(a.var())       #std=sqrt(var)

2.581988897471611

In [474]:
a.std()     #standard deviation

2.581988897471611

In [475]:
a.sum(0)  #calculating sum vertically or column wise  but in pandas it is row wise 

array([12, 15, 18])

In [476]:
a.sum(1)  # for horizontal opration  use sum(1)

array([ 6, 15, 24])

In [477]:
a.mean(0)

array([4., 5., 6.])

In [478]:
a.mean(1)

array([2., 5., 8.])

In [44]:
c=np.arange(1,10)

In [45]:
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [482]:
np.sqrt(c)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [47]:
np.sum(c)       #method 1

45

In [46]:
c.sum()         #method 2

45

In [485]:
np.exp(c)   # e^power

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [29]:
np.random.randint(1,101,size=10)      # np library.fun.command   # method 1      # for any random integer

array([56, 69, 21, 68, 98, 65, 16, 81, 99, 89])

In [71]:
from numpy.random import randint
                                             # method 2

In [498]:
randint(1,101,10)

array([39, 42, 73, 63, 85, 16, 30, 68, 36, 33])

In [58]:
c=np.random.randn(10) 
c                   # random no. b/w -o to +0

array([ 1.24256811,  0.50289455, -0.2243904 ,  0.02973254,  1.98501332,
        0.32150371,  0.00414141,  0.06986961,  0.23144656,  0.21788427])

In [59]:
c.mean()

0.4380663670052842

In [60]:
c.std()

0.6386450166275516

In [512]:
np.random.rand(10)          # random no. b/w o and 1

array([0.50109098, 0.52827548, 0.51927028, 0.97387363, 0.72780499,
       0.35763694, 0.59416743, 0.21752943, 0.02531654, 0.25943121])

In [18]:
a=np.random.randint(1,100,10)
b=np.random.randint(1,100,10)
a

array([47, 49, 95, 24, 94, 55, 54, 98, 27, 24])

In [19]:
b

array([42, 96, 59, 10, 15, 59, 99, 32, 31,  9])

In [20]:
np.maximum(a,b)       # for best of two from two array,it will compare with same location value and return as maximum value of that place

array([47, 96, 95, 24, 94, 59, 99, 98, 31, 24])

In [21]:
np.minimum(a,b) #check best of two array and return output

array([42, 49, 59, 10, 15, 55, 54, 32, 27,  9])

In [22]:
a.max()       # use max and min for array max and min value of that particular array not for comparing two array

98

In [23]:
b.min()

9

In [24]:
a=np.array([True,False,True])
a

array([ True, False,  True])

In [25]:
a.any()     # for comparing with any of array and if condition is true then result is true

True

In [26]:
a.all()           # for comparing with all of array and if all condition are true then result is true

False

In [549]:
b=np.array([True,True,True])
b

array([ True,  True,  True])

In [550]:
b.all()

True

In [551]:
b.any()

True

In [552]:
c=np.array([False,False,False])
c

array([False, False, False])

In [553]:
c.any() # if compare with any then result is false as all are false

False

In [555]:
c.all()  # no all are true so false

False

In [72]:
b=randint(1,101,10)
b

array([87, 62, 36, 51, 76,  7, 70, 39, 90, 71])

In [50]:
randint(1,101,10)>100


array([False, False, False, False, False, False, False, False, False,
       False])

In [558]:
b<40       #direct compare in numpy

array([ True, False, False,  True, False,  True,  True,  True, False,
       False])

In [565]:
a=np.array([1,2,3])
b=np.array([10,20,30])
c=np.array([True,False,True])

In [567]:
np.where(c,a,b)            # where(condition,True,False)  # if condition is satisfied either true or false,it will print a otherwise b as 
                    format(condition;if satisfied then print the next to the comma, print a if condition satisfy,else print b  )

array([ 1, 20,  3])

In [51]:
a=np.arange(1,5,1).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [52]:
b=np.arange(10,41,10).reshape(2,2)
b

array([[10, 20],
       [30, 40]])

In [53]:
c=np.array([[True,True],[False,False]])
c

array([[ True,  True],
       [False, False]])

In [60]:
np.where(c,b,a) # c is satisfy so print b else a

array([[10, 20],
       [ 3,  4]])

In [30]:
a=np.array([3,5,9])
a

array([3, 5, 9])

In [31]:
b=np.array([5,1,11])
b

array([ 5,  1, 11])

In [34]:
c=[a,b]
c

[array([3, 5, 9]), array([ 5,  1, 11])]

In [577]:
np.stack([a,b])         # stacking it into a matrix

array([[ 3,  5,  9],
       [ 5,  1, 11]])

In [583]:
np.stack([a,b],axis=1)         # fun of stack where axis convert into vertical

array([[ 3,  5],
       [ 5,  1],
       [ 9, 11]])

In [588]:
np.stack([a,b],axis=0)               #by default

array([[ 3,  5,  9],
       [ 5,  1, 11]])

In [584]:
type(np.stack([a,b]))        # we use multiple fun which is not used in array like axis

numpy.ndarray

In [585]:
np.array([a,b])

array([[ 3,  5,  9],
       [ 5,  1, 11]])

In [586]:
type(np.array([a,b]))           # pass as list or tuple both are same

numpy.ndarray

In [587]:
np.column_stack([a,b])        # directly change in axis  or map a

array([[ 3,  5],
       [ 5,  1],
       [ 9, 11]])

In [590]:
np.hstack([a,b])          # map data horizontally

array([ 3,  5,  9,  5,  1, 11])

In [591]:
np.vstack([a,b])   # map them vertically       same as stack

array([[ 3,  5,  9],
       [ 5,  1, 11]])

In [4]:
import numpy as np
a=np.array([1,2,3])
b=np.array([10,20,30])
d=np.dstack([a,b])     #3d array  #for here 2d are showing and 1 is on back of x or slicing
d

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]]])

In [6]:
np.ndim(d)             # for knowing dimention    

3

In [8]:
d.shape

(1, 3, 2)

In [9]:
b=np.arange(1,10).reshape(3,3)

In [10]:
for i in b:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
